version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:16.0
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: main
    ports:
      - "5400:5432"

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6300:6379"
    environment:
      - REDIS_PASSWORD=secret

  elasticsearch:
    image: elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"

  s3:
    image: quay.io/minio/minio:latest
    command: minio server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: secretsecret
      MINIO_ACCESS_KEY: secretsecret
      MINIO_SECRET_KEY: secretsecret
      MINIO_DOMAIN: s3
    restart: always
    volumes:
      - ./data:/data

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://localhost:9000 minio secretsecret; /usr/bin/mc mb myminio/open; /usr/bin/mc anonymous set public myminio/open; exit 0; "

  createbuckets2:
    image: minio/mc:latest
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://localhost:9000 minio secretsecret; /usr/bin/mc mb myminio/priv; /usr/bin/mc anonymous set public myminio/priv; exit 0; "

  jaeger:
    image: jaegertracing/all-in-one:1.27
    restart: always
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - "9100:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka

